# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 21:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_auto_20161220_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extension',
            field=models.CharField(default='mp4', max_length=10),
        ),
    ]
