# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 21:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0005_video_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='extension',
        ),
    ]
