# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-20 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0006_remove_video_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='extension',
            field=models.CharField(default='mp4', max_length=4),
        ),
    ]
