# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 17:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0007_video_extension'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='extension',
        ),
    ]
