# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-05 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0008_remove_video_extension'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.CharField(default='http://cdn.wallpapersafari.com/58/12/nyHXSO.jpg', max_length=2000),
        ),
        migrations.AddField(
            model_name='proj',
            name='image',
            field=models.CharField(default='http://cdn.wallpapersafari.com/58/12/nyHXSO.jpg', max_length=2000),
        ),
    ]
