# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-06-18 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0018_utilisateur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='public',
        ),
        migrations.AddField(
            model_name='video',
            name='category',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='videos.Category'),
        ),
    ]
