# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-20 20:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0020_auto_20170618_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorite',
            name='also_favorite',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='favorite_proj',
            name='also_favorite',
            field=models.BooleanField(default=False),
        ),
    ]
