# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-06-25 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0022_auto_20170620_2045'),
    ]

    operations = [
        migrations.AddField(
            model_name='proj',
            name='description',
            field=models.CharField(default='Pas de description disponible.', max_length=1000),
        ),
    ]
