# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-12 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0026_utilisateur_promo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='url',
            new_name='hd',
        ),
        migrations.AddField(
            model_name='video',
            name='promo',
            field=models.IntegerField(default=2015),
        ),
    ]
