# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-12 16:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0027_auto_20170912_1643'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='md',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='video',
            name='screenshot',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='video',
            name='sd',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='video',
            name='hd',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
