# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-09-26 13:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0028_auto_20170912_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='subtitles',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
