# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-09-27 17:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0029_video_subtitles'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(default='rgba(26, 188, 156,1.0)', max_length=100),
        ),
        migrations.AddField(
            model_name='category',
            name='titre_short',
            field=models.CharField(default='cat', max_length=100),
        ),
    ]
